workspace:
  base: /go
  path: src/github.com/karantin2020/mattermost-images

pipeline:
  server:
    image: golang:1.9.0-alpine3.6
    commands:
      - apk add --update git build-base
      - git clone --depth 1 --branch v4.2.0 https://github.com/mattermost/mattermost-server $GOPATH/src/github.com/mattermost/platform
      - go get -u -v github.com/Masterminds/glide
      - cd $GOPATH/src/github.com/mattermost/platform
      - glide install
      - make build-linux BUILD_NUMBER=4.2.0
      - ls $GOPATH/bin
      - $GOPATH/bin/platform -h
